/*
-- Query: SELECT * FROM rt.critics
LIMIT 0, 1000

-- Date: 2019-02-05 17:27
*/
CREATE TABLE `critics` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `top_critic` tinyint(1) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `img_url` varchar(255) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=452 DEFAULT CHARSET=latin1;

INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (1,0,'Carla Renata','/img/user_none.jpg','The Curvy Film Critic');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (2,0,'Filipe Freitas','http://lorempixel.com/50/50/people/','Always Good Movies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (3,0,'Andrea Thompson','/img/user_none.jpg','Cultured Vultures ');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (4,0,'Kyle Pinion','http://lorempixel.com/50/50/people/','The Beat');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (5,0,'Emmanuel Noisette','/img/user_none.jpg','The Movie Blog');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (6,0,'Rachel Wagner','http://lorempixel.com/50/50/people/','Rotoscopers');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (7,0,'Evan Dossey','/img/user_none.jpg','Midwest Film Journal');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (8,0,'Nathalia Aryani','http://lorempixel.com/50/50/people/','San Diego Entertainer');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (9,0,'Federico Furzan','/img/user_none.jpg','Cinelipsis');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (10,1,'Lawrence Ware','http://lorempixel.com/50/50/people/','New York Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (11,0,'Emily Asher-Perrin','/img/user_none.jpg','Tor.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (12,0,'Matt Brunson','http://lorempixel.com/50/50/people/','Film Frenzy');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (13,0,'John Beifuss','/img/user_none.jpg','Commercial Appeal (Memphis, TN)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (14,0,'Tim Stevens','http://lorempixel.com/50/50/people/','Comicsverse');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (15,0,'Matt Hudson','/img/user_none.jpg','What I Watched Tonight');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (16,0,'Sheraz Farooqi','http://lorempixel.com/50/50/people/','ComicBook Debate');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (17,0,'Pablo Fernandez','/img/user_none.jpg','Vix');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (18,0,'Colby Bryant','http://lorempixel.com/50/50/people/','Colbybryant.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (19,0,'John Hanlon','/img/user_none.jpg','Big Hollywood');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (20,0,'Brian Gill','http://lorempixel.com/50/50/people/','Mad About Movies Podcast');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (21,0,'Sharronda Williams','/img/user_none.jpg','Pay Or Wait');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (22,0,'Kt Schaefer','http://lorempixel.com/50/50/people/','Substream Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (23,0,'Matt Ward','/img/user_none.jpg','Cinematic Considerations');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (24,0,'Debbie Lynn Elias','http://lorempixel.com/50/50/people/','Behind The Lens');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (25,0,'Matt Oakes','/img/user_none.jpg','Silver Screen Riot');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (26,0,'PJ Nabarro','http://lorempixel.com/50/50/people/','Patrick Nabarro');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (27,0,'Cameron Frew','/img/user_none.jpg','FrewFilm');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (28,0,'Jennifer Heaton','http://lorempixel.com/50/50/people/','Alternative Lens');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (29,0,'Khal Davenport','/img/user_none.jpg','Complex');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (30,0,'VyceVictus','http://lorempixel.com/50/50/people/','Lewton Bus');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (31,0,'Bob Chipman','/img/user_none.jpg','Geek');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (32,0,'Zaki Hasan','http://lorempixel.com/50/50/people/','Sequart');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (33,0,'Johnny Gayzmonic','/img/user_none.jpg','Fanboys of the Universe');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (34,0,'Sean Mulvihill','http://lorempixel.com/50/50/people/','FanboyNation.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (35,0,'Joel Mayward','/img/user_none.jpg','Cinemayward');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (36,0,'Doug Jamieson','http://lorempixel.com/50/50/people/','The Jam Report');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (37,0,'Clint Worthington','/img/user_none.jpg','The Spool');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (38,0,'Micheal Compton','http://lorempixel.com/50/50/people/','Bowling Green Daily News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (39,0,'Aaron Leggo','/img/user_none.jpg','Sloths and Movies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (40,0,'Tomas Trussow','http://lorempixel.com/50/50/people/','The Lonely Film Critic');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (41,0,'Nguyen Le','/img/user_none.jpg','InSession Film');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (42,0,'Alan French','http://lorempixel.com/50/50/people/','We Bought a Blog');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (43,0,'Leona Laurie','/img/user_none.jpg','Geek Girl Authority');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (44,0,'Ross Miller','http://lorempixel.com/50/50/people/','The National (Scotland)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (45,0,'Funmi Sunmonu','/img/user_none.jpg','Add This To Your List');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (46,0,'Danielle Radford','http://lorempixel.com/50/50/people/','Screen Junkies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (47,0,'Roth Cornet','/img/user_none.jpg','Screen Junkies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (48,0,'Jared Mobarak','http://lorempixel.com/50/50/people/','BuffaloVibe');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (49,0,'Mark Kermode','/img/user_none.jpg','Kermode & Mayo\'s Film Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (50,0,'Hope Madden','http://lorempixel.com/50/50/people/','Columbus Underground');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (51,0,'Akhil Arora','/img/user_none.jpg','Gadgets360');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (52,0,'Abbie Bernstein','http://lorempixel.com/50/50/people/','Assignment X');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (53,0,'Adam Epstein','/img/user_none.jpg','Quartz');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (54,0,' Nicholas Bell','http://lorempixel.com/50/50/people/','IONCINEMA.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (55,0,'Robert Daniels','/img/user_none.jpg','812filmreviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (56,0,'Terence Johnson','http://lorempixel.com/50/50/people/','Le Noir Auteur');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (57,0,'Kiera Allen','/img/user_none.jpg','Daily Journal (Kankakee, IL)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (58,0,'Alci Rengifo','http://lorempixel.com/50/50/people/','Entertainment Voice');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (59,0,'Rendy Jones','/img/user_none.jpg','Rendy Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (60,0,'Kimberly Pierce','http://lorempixel.com/50/50/people/','Geek Girl Authority');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (61,0,'Annie Banks','/img/user_none.jpg','Glue Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (62,0,'Khari J. Sampson','http://lorempixel.com/50/50/people/','Gwinnett Daily Post (GA)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (63,0,'Stephanie Watts','/img/user_none.jpg','One Room With A View');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (64,0,'Deirdre Crimmins','http://lorempixel.com/50/50/people/','Daily Grindhouse');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (65,0,'Mae Abdulbaki','/img/user_none.jpg','Movies with Mae');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (66,0,'Lisa Johnson Mandell','http://lorempixel.com/50/50/people/','AtHomeInHollywood.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (67,0,'Jazz Tangcay','/img/user_none.jpg','Awards Daily');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (68,0,'Kathryn Reklis','http://lorempixel.com/50/50/people/','The Christian Century');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (69,0,'Lapacazo Sandoval','/img/user_none.jpg','New York Amsterdam News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (70,1,'Mikey Mason','http://lorempixel.com/50/50/people/','Geeks of Color');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (71,0,'Tom Santilli','/img/user_none.jpg','AXS.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (72,0,'A.S. Hamrah','http://lorempixel.com/50/50/people/','n+1');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (73,0,'Clover Hope','/img/user_none.jpg','The Muse/Jezebel');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (74,0,'Wesley Lovell','http://lorempixel.com/50/50/people/','Cinema Sight');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (75,0,'Tom Fitzgerald and Lorenzo Marquez','/img/user_none.jpg','Tom & Lorenzo');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (76,0,'Michael A. Smith','http://lorempixel.com/50/50/people/','MediaMikes');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (77,0,'TK Burton','/img/user_none.jpg','Pajiba');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (78,0,'Rob Gonsalves','http://lorempixel.com/50/50/people/','eFilmCritic.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (79,0,'Anna Deavere Smith','/img/user_none.jpg','The New York Review of Books');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (80,0,'James Kendrick','http://lorempixel.com/50/50/people/','Q Network Film Desk');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (81,0,'Rich Cline','/img/user_none.jpg','Shadows on the Wall');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (82,0,'Damian Levy','http://lorempixel.com/50/50/people/','Jamaica Gleaner');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (83,0,'John Serba','/img/user_none.jpg','MLive.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (84,0,'David Nusair','http://lorempixel.com/50/50/people/','Reel Film Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (85,0,'Loren King','/img/user_none.jpg','Newport This Week (RI)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (86,0,'Cole Smithey','http://lorempixel.com/50/50/people/','ColeSmithey.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (87,0,'Jason Di Rosso','/img/user_none.jpg','The Hub on Screen');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (88,0,'Sarah Ward','http://lorempixel.com/50/50/people/','Concrete Playground');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (89,0,'Matthew Pejkovic','/img/user_none.jpg','Matt\'s Movie Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (90,0,'Shaun Munro','http://lorempixel.com/50/50/people/','Flickering Myth');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (91,0,'Molly Laich','/img/user_none.jpg','Missoula Independent');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (92,0,'Monique Jones','http://lorempixel.com/50/50/people/','Slashfilm');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (93,0,'Pablo Villaça','/img/user_none.jpg','Cinema em Cena');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (94,0,'Alexis Nedd','http://lorempixel.com/50/50/people/','Cosmopolitan');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (95,0,'Jim Lane','/img/user_none.jpg','Sacramento News & Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (96,0,'Matthew Toomey','http://lorempixel.com/50/50/people/','ABC Radio Brisbane');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (97,0,'Amelia Navascues','/img/user_none.jpg','Triple J');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (98,0,'J. Olson','http://lorempixel.com/50/50/people/','Cinemixtape');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (99,0,'Ruben Peralta Rigaud','/img/user_none.jpg','Cocalecas');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (100,0,'Michael Sragow','http://lorempixel.com/50/50/people/','Film Comment Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (101,0,'Daniel Krauze','/img/user_none.jpg','El Financiero');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (102,0,'Robert Evers','http://lorempixel.com/50/50/people/','PopMatters');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (103,0,'Diane Pershing','/img/user_none.jpg','Malibu Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (104,0,'Linda Cook','http://lorempixel.com/50/50/people/','Quad City Times (Davenport, IA)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (105,0,'José Martín','/img/user_none.jpg','El antepenúltimo mohicano');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (106,0,'Rafael Rosales Santos','http://lorempixel.com/50/50/people/','Konexión');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (107,0,'Carlos Díaz Reyes','/img/user_none.jpg','Vanguardia (Mexico)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (108,0,'Tim Brayton','http://lorempixel.com/50/50/people/','Alternate Ending');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (109,0,'Sebastian Zavala Kahn','/img/user_none.jpg','Cinencuentro');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (110,0,'Lee Jutton','http://lorempixel.com/50/50/people/','Film Inquiry');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (111,0,'Bob Grimm','/img/user_none.jpg','Reno News and Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (112,0,'Hanif Abdurraqib','http://lorempixel.com/50/50/people/','4Columns');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (113,0,'Frederic and Mary Ann Brussat','/img/user_none.jpg','Spirituality and Practice');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (114,0,'Tony Macklin','http://lorempixel.com/50/50/people/','tonymacklin.net');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (115,0,'Dennis Schwartz','/img/user_none.jpg','Ozus\' World Movie Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (116,0,'Beth Accomando','http://lorempixel.com/50/50/people/','KPBS.org');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (117,0,'Juanma Fernández París','/img/user_none.jpg','El Nuevo Día');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (118,0,'tt stern-enzi','http://lorempixel.com/50/50/people/','Dayton CityPaper');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (119,0,'Jake Pesaruk','/img/user_none.jpg','Vue Weekly (Edmonton, Alberta)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (120,0,'Helen Lewis','http://lorempixel.com/50/50/people/','New Statesman');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (121,0,'Stuart Klawans','/img/user_none.jpg','The Nation');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (122,0,'Namwali Serpell','http://lorempixel.com/50/50/people/','The New York Review of Books');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (123,0,'Esau McCaulley','/img/user_none.jpg','Christianity Today');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (124,0,'Alex Doenau','http://lorempixel.com/50/50/people/','Trespass');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (125,0,'Gary Dowell','/img/user_none.jpg','Dark Horizons');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (126,0,'Tara Thorne','http://lorempixel.com/50/50/people/','The Coast (Halifax, Nova Scotia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (127,0,'Dorothy Woodend','/img/user_none.jpg','The Tyee (British Columbia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (128,0,'Al Hoff','http://lorempixel.com/50/50/people/','Pittsburgh City Paper');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (129,0,'Kristen Lopez','/img/user_none.jpg','Culturess');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (130,0,'Lauren Terry','http://lorempixel.com/50/50/people/','Willamette Week');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (131,0,'Kam Williams','/img/user_none.jpg','Baret News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (132,0,'Margot Harrison','http://lorempixel.com/50/50/people/','Seven Days');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (133,0,'Robert Roten','/img/user_none.jpg','Laramie Movie Scope');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (134,0,'William Venegas','http://lorempixel.com/50/50/people/','La Nación (Costa Rica)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (135,0,'CJ Johnson','/img/user_none.jpg','ABC Radio (Australia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (136,0,'Luis Martínez','http://lorempixel.com/50/50/people/','El Mundo (Spain)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (137,0,'Jonathan Sánchez','/img/user_none.jpg','Butaca Ancha');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (138,0,'Jeff Beck','http://lorempixel.com/50/50/people/','The Blu Spot');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (139,0,'Alejandro Turdo','/img/user_none.jpg','EscribiendoCine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (140,0,'Emmanuel Báez','http://lorempixel.com/50/50/people/','Cinéfiloz');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (141,0,'Erick Ortiz','/img/user_none.jpg','Butaca Ancha');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (142,0,'Andre Meadows','http://lorempixel.com/50/50/people/','Black Nerd Comedy');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (143,0,'Brian Grubb','/img/user_none.jpg','Uproxx');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (144,0,'Mathew DeKinder','http://lorempixel.com/50/50/people/','Suburban Journals of St. Louis');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (145,0,'Felix Vasquez Jr.','/img/user_none.jpg','Cinema Crazed');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (146,0,'Sarah Marrs','http://lorempixel.com/50/50/people/','Lainey Gossip');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (147,0,'Kevin A. Ranson','/img/user_none.jpg','MovieCrypt.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (148,0,'Ernesto Diezmartinez','http://lorempixel.com/50/50/people/','Cine Vértigo');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (149,0,'Daniel M. Kimmel','/img/user_none.jpg','New England Movies Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (150,0,'Andy Lea','http://lorempixel.com/50/50/people/','Daily Express (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (151,1,'Matthew Rozsa','/img/user_none.jpg','Salon.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (152,0,'Sean Burns','http://lorempixel.com/50/50/people/','Spliced Personality');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (153,0,'Tom Shone','/img/user_none.jpg','Sunday Times (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (154,0,'Andrea Chase','http://lorempixel.com/50/50/people/','Killer Movie Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (155,0,'Tim Martain','/img/user_none.jpg','The Mercury');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (156,0,'Jordan Ruimy','http://lorempixel.com/50/50/people/','World of Reel');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (157,0,'Aine O\'Connor','/img/user_none.jpg','Sunday Independent (Ireland)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (158,0,'Pete Vonder Haar','http://lorempixel.com/50/50/people/','Houston Press');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (159,0,'Diva Velez','/img/user_none.jpg','TheDivaReview.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (160,0,'Robin Clifford','http://lorempixel.com/50/50/people/','Reeling Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (161,1,'Christopher Orr','/img/user_none.jpg','The Atlantic');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (162,0,'Ed Whitfield','http://lorempixel.com/50/50/people/','The Ooh Tray');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (163,0,'John Urbancich','/img/user_none.jpg','Your Movies (cleveland.com)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (164,0,'Katherine Monk','http://lorempixel.com/50/50/people/','Ex-Press.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (165,0,'Eli Glasner','/img/user_none.jpg','CBC News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (166,0,'Alachia Queen ','http://lorempixel.com/50/50/people/','Alachia Queen');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (167,0,'Jackie K. Cooper','/img/user_none.jpg','jackiekcooper.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (168,0,'Jim Schembri','http://lorempixel.com/50/50/people/','3AW');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (169,0,'Craig Takeuchi','/img/user_none.jpg','Georgia Straight');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (170,0,'Rubin Safaya','http://lorempixel.com/50/50/people/','Cinemalogue');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (171,0,'Roe McDermott','/img/user_none.jpg','Hot Press');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (172,0,'Randall King','http://lorempixel.com/50/50/people/','Winnipeg Free Press');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (173,0,'Udita Jhunjhunwala','/img/user_none.jpg','Scroll.in');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (174,0,'Mike McGranaghan','http://lorempixel.com/50/50/people/','Aisle Seat');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (175,1,'J. R. Jones','/img/user_none.jpg','Chicago Reader');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (176,0,'Matthew Norman ','http://lorempixel.com/50/50/people/','London Evening Standard');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (177,0,'Annlee Ellingson','/img/user_none.jpg','L.A. Biz');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (178,0,'Piers Marchant','http://lorempixel.com/50/50/people/','Arkansas Democrat-Gazette');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (179,0,'Jazmine Joyner','/img/user_none.jpg','Slashfilm');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (180,0,'Charles Pulliam-Moore','http://lorempixel.com/50/50/people/','io9.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (181,0,'Michael Fairbanks','/img/user_none.jpg','The Young Folks');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (182,0,'Jenni Moore','http://lorempixel.com/50/50/people/','The Stranger (Seattle, WA)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (183,1,'Anthony Lane','/img/user_none.jpg','New Yorker');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (184,0,'Peter Sobczynski','http://lorempixel.com/50/50/people/','eFilmCritic.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (185,1,'Peter Rainer','/img/user_none.jpg','Christian Science Monitor');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (186,0,'Max Weiss','http://lorempixel.com/50/50/people/','Baltimore Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (187,0,'Armond White','/img/user_none.jpg','National Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (188,0,'Saskia Baron','http://lorempixel.com/50/50/people/','The Arts Desk');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (189,0,'Brooke Corso','/img/user_none.jpg','The Monitor (McAllen, TX)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (190,0,'Josh Terry','http://lorempixel.com/50/50/people/','Deseret News (Salt Lake City)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (191,0,'Bernard Boo','/img/user_none.jpg','PopMatters');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (192,0,'Tom Meek','http://lorempixel.com/50/50/people/','Cambridge Day');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (193,0,'Leonard Maltin','/img/user_none.jpg','leonardmaltin.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (194,0,'Neil Miller','http://lorempixel.com/50/50/people/','Film School Rejects');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (195,0,'Sergio López Aguirre','/img/user_none.jpg','Cine Premiere');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (196,0,'Masego Panyane','http://lorempixel.com/50/50/people/','Independent Online (South Africa)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (197,0,'Jamal-Dean Grootboom','/img/user_none.jpg','Independent Online (South Africa)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (198,0,'Kanin Srimaneekulroj','http://lorempixel.com/50/50/people/','Bangkok Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (199,0,'Richard von Busack','/img/user_none.jpg','MetroActive');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (200,0,'Eder Campuzano','http://lorempixel.com/50/50/people/','Oregonian');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (201,0,'Abby Olcese','/img/user_none.jpg','Sojourners');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (202,0,'Rashid Irani','http://lorempixel.com/50/50/people/','Hindustan Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (203,0,'Rain Jokinen','/img/user_none.jpg','MullingMovies.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (204,0,'Kelli Weston','http://lorempixel.com/50/50/people/','Sight and Sound');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (205,0,'Laura Clifford','/img/user_none.jpg','Reeling Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (206,0,'Megan Basham','http://lorempixel.com/50/50/people/','WORLD');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (207,1,'Matthew Lickona','/img/user_none.jpg','San Diego Reader');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (208,0,'Vesper Arnett','http://lorempixel.com/50/50/people/','Brightest Young Things');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (209,0,'Sandie Angulo Chen','/img/user_none.jpg','Common Sense Media');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (210,0,'Stephen Silver','http://lorempixel.com/50/50/people/','Splice Today');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (211,0,'Kiko Martinez','/img/user_none.jpg','San Antonio Current ');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (212,0,'Charles Koplinski','http://lorempixel.com/50/50/people/','Illinois Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (213,0,'Roxana Hadadi','/img/user_none.jpg','Chesapeake Family Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (214,0,'Christian Toto','http://lorempixel.com/50/50/people/','HollywoodInToto.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (215,0,'Phil Villarreal','/img/user_none.jpg','ABC Tucson');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (216,0,'Kurt Loder','http://lorempixel.com/50/50/people/','Reason Online');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (217,0,'Conor O\'Donnell','/img/user_none.jpg','The Film Stage');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (218,0,'Sonny Bunch','http://lorempixel.com/50/50/people/','Washington Free Beacon');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (219,0,'Matt Neal','/img/user_none.jpg','ABC Radio (Australia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (220,0,'Steve Crum','http://lorempixel.com/50/50/people/','Video-Reviewmaster.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (221,0,'Rohan Naahar','/img/user_none.jpg','Hindustan Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (222,0,'Eric Melin','http://lorempixel.com/50/50/people/','Pitch.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (223,0,'Brian Viner','/img/user_none.jpg','Daily Mail (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (224,0,'Christopher Llewellyn Reed','http://lorempixel.com/50/50/people/','Film Festival Today');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (225,0,'Rebecca Murray','/img/user_none.jpg','Showbiz Junkies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (226,0,'Susan Granger','http://lorempixel.com/50/50/people/','SSG Syndicate');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (227,0,'Lili Loofbourow','/img/user_none.jpg','The Week');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (228,0,'Tim Appelo','http://lorempixel.com/50/50/people/','AARP Movies for Grownups');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (229,1,'John Wenzel','/img/user_none.jpg','Denver Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (230,0,'Diego Batlle','http://lorempixel.com/50/50/people/','La Nación (Argentina)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (231,0,'Kirk Baird','/img/user_none.jpg','Toledo Blade');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (232,0,'Eric D. Snider','http://lorempixel.com/50/50/people/','EricDSnider.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (233,0,'Jamie East','/img/user_none.jpg','The Sun (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (234,0,'Jeffrey M. Anderson','http://lorempixel.com/50/50/people/','San Francisco Examiner');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (235,0,'Carl Kozlowski','/img/user_none.jpg','Pasadena Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (236,0,'Christopher Lawrence','http://lorempixel.com/50/50/people/','Las Vegas Review-Journal');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (237,0,'Mario Alegre','/img/user_none.jpg','Próxima Tanda');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (238,0,'Vincent Mancini','http://lorempixel.com/50/50/people/','FilmDrunk');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (239,0,'Robert Denerstein','/img/user_none.jpg','Denerstein Unleashed');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (240,0,'David \'Mad Dog\' Bradley','http://lorempixel.com/50/50/people/','Adelaide Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (241,0,'James Verniere','/img/user_none.jpg','Boston Herald');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (242,0,'Dwight Brown','http://lorempixel.com/50/50/people/','National Newspaper Publishers Association ');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (243,0,'Nick Bhasin','/img/user_none.jpg','sbs.com.au');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (244,0,'Devesh Sharma','http://lorempixel.com/50/50/people/','Filmfare');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (245,0,'Tony Norman','/img/user_none.jpg','Pittsburgh Post-Gazette');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (246,0,'Alex Abad-Santos','http://lorempixel.com/50/50/people/','Vox');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (247,0,'David Medsker','/img/user_none.jpg','Bullz-Eye.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (248,1,'Jamelle Bouie','http://lorempixel.com/50/50/people/','Slate');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (249,0,'MaryAnn Johanson','/img/user_none.jpg','Flick Filosopher');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (250,0,'Roger Tennis','http://lorempixel.com/50/50/people/','Cinemaclips.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (251,0,'Mark Dujsik','/img/user_none.jpg','Mark Reviews Movies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (252,0,'Pablo A. Scholz','http://lorempixel.com/50/50/people/','Clarín');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (253,0,'Xavi Sánchez Pons','/img/user_none.jpg','Sensacine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (254,0,'Julian Chambliss','http://lorempixel.com/50/50/people/','Orlando Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (255,0,'Charles Mudede','/img/user_none.jpg','The Stranger (Seattle, WA)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (256,1,'Odie Henderson','http://lorempixel.com/50/50/people/','RogerEbert.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (257,1,'Calvin Wilson','/img/user_none.jpg','St. Louis Post-Dispatch');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (258,0,'Rob Carnevale','http://lorempixel.com/50/50/people/','Indie London');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (259,0,'Ryan Gilbey','/img/user_none.jpg','New Statesman');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (260,0,'Dustin Putman','http://lorempixel.com/50/50/people/','TheFilmFile.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (261,0,'Brad Keefe','/img/user_none.jpg','Columbus Alive');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (262,0,'Maren Longbella','http://lorempixel.com/50/50/people/','St. Paul Pioneer Press');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (263,0,'Radheyan Simonpillai','/img/user_none.jpg','NOW Toronto');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (264,0,'Larushka Ivan-Zadeh','http://lorempixel.com/50/50/people/','Metro (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (265,0,'Boon Chan','/img/user_none.jpg','The Straits Times (Singapore)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (266,0,'Richard Whittaker','http://lorempixel.com/50/50/people/','Austin Chronicle');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (267,0,'Alan Zilberman','/img/user_none.jpg','Washington City Paper');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (268,1,'Karen D\'Souza','http://lorempixel.com/50/50/people/','San Jose Mercury News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (269,0,'Jim Judy','/img/user_none.jpg','Screen It!');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (270,0,'Robert Horton','http://lorempixel.com/50/50/people/','Seattle Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (271,0,'Dana Barbuto','/img/user_none.jpg','The Patriot Ledger');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (272,0,'Jonathan W. Hickman','http://lorempixel.com/50/50/people/','Daily Film Fix');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (273,0,'Shelagh Rowan-Legg','/img/user_none.jpg','ScreenAnarchy');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (274,0,'Neil Pond','http://lorempixel.com/50/50/people/','Parade Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (275,0,'Avi Offer','/img/user_none.jpg','NYC Movie Guru');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (276,0,'Rob Hunter','http://lorempixel.com/50/50/people/','Film School Rejects');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (277,0,'Michelle Alexandria','/img/user_none.jpg','Eclipse Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (278,0,'Jeffrey Lyles','http://lorempixel.com/50/50/people/','Lyles\' Movie Files');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (279,0,'Brian Orndorf','/img/user_none.jpg','Blu-ray.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (280,0,'Frank Swietek','http://lorempixel.com/50/50/people/','One Guy\'s Opinion');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (281,0,'Sandy Schaefer','/img/user_none.jpg','ScreenRant');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (282,1,'Dawn Burkes','http://lorempixel.com/50/50/people/','Dallas Morning News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (283,0,'André Hereford','/img/user_none.jpg','Metro Weekly (Washington, DC)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (284,0,'Nell Minow','http://lorempixel.com/50/50/people/','Movie Mom');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (285,0,'Chris Stuckmann','/img/user_none.jpg','ChrisStuckmann.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (286,0,'Jeremy Jahns','http://lorempixel.com/50/50/people/','JeremyJahns.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (287,0,'Victoria Alexander','/img/user_none.jpg','FilmsInReview.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (288,0,'Sara Michelle Fetters','http://lorempixel.com/50/50/people/','MovieFreak.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (289,0,'Robert Kojder','/img/user_none.jpg','Flickering Myth');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (290,0,'Matt Donato','http://lorempixel.com/50/50/people/','We Got This Covered');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (291,0,'Dominick Suzanne-Mayer ','/img/user_none.jpg','Consequence of Sound');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (292,0,'Blake Crane','http://lorempixel.com/50/50/people/','Film Pulse');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (293,0,'Gary Thompson','/img/user_none.jpg','Philadelphia Daily News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (294,1,'Bill Goodykoontz','http://lorempixel.com/50/50/people/','Arizona Republic');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (295,1,'James Berardinelli','/img/user_none.jpg','ReelViews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (296,0,'Iain McNally','http://lorempixel.com/50/50/people/','Starburst');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (297,0,'Joe Gross','/img/user_none.jpg','Austin American-Statesman');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (298,0,'Sean P. Means','http://lorempixel.com/50/50/people/','Salt Lake Tribune');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (299,0,'Kristian M. Lin','/img/user_none.jpg','Fort Worth Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (300,0,'Chris Knight','http://lorempixel.com/50/50/people/','National Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (301,0,'Gavia Baker-Whitelaw','/img/user_none.jpg','The Daily Dot');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (302,1,'Richard Roeper','http://lorempixel.com/50/50/people/','Chicago Sun-Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (303,0,'Greg Maki','/img/user_none.jpg','Star-Democrat (Easton, MD)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (304,0,'George Thomas','http://lorempixel.com/50/50/people/','Akron Beacon Journal');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (305,0,'Michael Sangiacomo','/img/user_none.jpg','Cleveland Plain Dealer');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (306,1,'Barry Hertz','http://lorempixel.com/50/50/people/','Globe and Mail');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (307,1,'Ty Burr','/img/user_none.jpg','Boston Globe');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (308,0,'Kyle Smith','http://lorempixel.com/50/50/people/','National Review');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (309,1,'Adam Graham','/img/user_none.jpg','Detroit News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (310,0,'Josh Larsen','http://lorempixel.com/50/50/people/','LarsenOnFilm');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (311,0,'Joanne Soh','/img/user_none.jpg','The New Paper (Singapore)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (312,0,'K. Austin Collins','http://lorempixel.com/50/50/people/','The Ringer');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (313,0,'Rob Vaux','/img/user_none.jpg','Action Figure Junkies ');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (314,0,'Gemma Creagh','http://lorempixel.com/50/50/people/','Film Ireland Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (315,0,'Dann Gire','/img/user_none.jpg','Chicago Daily Herald');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (316,0,'Dom Sinacola','http://lorempixel.com/50/50/people/','Paste Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (317,0,'Peter Canavese','/img/user_none.jpg','Groucho Reviews');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (318,0,'Fico Cangiano','http://lorempixel.com/50/50/people/','CineXpress');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (319,0,'Matthew Razak','/img/user_none.jpg','Flixist.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (320,0,'Travis Hopson','http://lorempixel.com/50/50/people/','Punch Drunk Critics');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (321,0,'Sinead Brennan','/img/user_none.jpg','RTÉ (Ireland)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (322,0,'Danielle Solzman','http://lorempixel.com/50/50/people/','Solzy at the Movies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (323,0,'Jim Slotek','/img/user_none.jpg','Original Cin');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (324,1,'Michael Phillips','http://lorempixel.com/50/50/people/','Chicago Tribune');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (325,1,'Mick LaSalle','/img/user_none.jpg','San Francisco Chronicle');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (326,1,'Ignatiy Vishnevetsky','http://lorempixel.com/50/50/people/','AV Club');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (327,1,'Moira MacDonald','/img/user_none.jpg','Seattle Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (328,1,'Sara Stewart','http://lorempixel.com/50/50/people/','New York Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (329,0,'Roger Moore','/img/user_none.jpg','Movie Nation');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (330,0,'Scott Chitwood','http://lorempixel.com/50/50/people/','ComingSoon.net');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (331,0,'Alan Cerny','/img/user_none.jpg','ComingSoon.net');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (332,0,'Zoe Margolis','http://lorempixel.com/50/50/people/','CineVue');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (333,0,'Joanna Langfield','/img/user_none.jpg','The Movie Minute');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (334,0,'Steve Persall','http://lorempixel.com/50/50/people/','Tampa Bay Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (335,0,'Liam Maguren','/img/user_none.jpg','Flicks.co.nz');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (336,0,'Yago García','http://lorempixel.com/50/50/people/','Cinemanía (Spain)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (337,1,'Katie Walsh','/img/user_none.jpg','Tribune News Service');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (338,0,'Graeme Tuckett','http://lorempixel.com/50/50/people/','Stuff.co.nz');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (339,0,'Steph Cozza','/img/user_none.jpg','Aggressive Comix');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (340,1,'Ann Hornaday','http://lorempixel.com/50/50/people/','Washington Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (341,0,'Stephen Romei','/img/user_none.jpg','The Australian');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (342,1,'Jonathan W. Gray','http://lorempixel.com/50/50/people/','The New Republic');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (343,0,'Jo Berry','/img/user_none.jpg','Movies4Kids');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (344,0,'Joseph Walsh','http://lorempixel.com/50/50/people/','The Skinny');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (345,0,'Matthew Turner','/img/user_none.jpg','iNews.co.uk');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (346,1,'Mara Reinstein','http://lorempixel.com/50/50/people/','Us Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (347,0,'Shyama Krishna Kumar','/img/user_none.jpg','Gulf News (UAE)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (348,0,'Chris Hunneysett','http://lorempixel.com/50/50/people/','Daily Mirror (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (349,0,'Chris Bumbray','/img/user_none.jpg','JoBlo\'s Movie Emporium');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (350,1,'Joshua Rothkopf','http://lorempixel.com/50/50/people/','Time Out');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (351,0,'Alex Bhattacharji','/img/user_none.jpg','Bloomberg News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (352,1,'Joe Morgenstern','http://lorempixel.com/50/50/people/','Wall Street Journal');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (353,0,'Wenlei Ma','/img/user_none.jpg','News.com.au');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (354,1,'Glen Weldon','http://lorempixel.com/50/50/people/','NPR');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (355,0,'Simon Miraudo','/img/user_none.jpg','Student Edge');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (356,0,'Paul Whitington','http://lorempixel.com/50/50/people/','Irish Independent');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (357,0,'Vicky Roach','/img/user_none.jpg','Daily Telegraph (Australia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (358,0,'Chris Wasser','http://lorempixel.com/50/50/people/','The Herald (Ireland)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (359,0,'Matthew Bond','/img/user_none.jpg','The Mail on Sunday (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (360,1,'Cary Darling','http://lorempixel.com/50/50/people/','Houston Chronicle');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (361,0,'Wendy Ide','/img/user_none.jpg','Observer (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (362,0,'Damien Straker','http://lorempixel.com/50/50/people/','Impulse Gamer');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (363,0,'Norman Wilner','/img/user_none.jpg','NOW Toronto');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (364,1,'Kristen Yoonsoo Kim','http://lorempixel.com/50/50/people/','Village Voice');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (365,0,'Anne Cohen','/img/user_none.jpg','Refinery29');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (366,0,'Hannah Woodhead','http://lorempixel.com/50/50/people/','Little White Lies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (367,0,'Ali Gray','/img/user_none.jpg','TheShiznit.co.uk');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (368,0,'Steven D. Greydanus','http://lorempixel.com/50/50/people/','National Catholic Register');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (369,0,'Louise Keller','/img/user_none.jpg','Urban Cinefile');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (370,0,'Rick Bentley','http://lorempixel.com/50/50/people/','Tribune News Service');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (371,0,'Stephen Rebello','/img/user_none.jpg','Playboy Online');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (372,0,'Tobi Akingbade','http://lorempixel.com/50/50/people/','Metro (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (373,0,'Stefan Pape','/img/user_none.jpg','HeyUGuys');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (374,0,'Keith Uhlich','http://lorempixel.com/50/50/people/','Slant Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (375,0,'Yolanda Machado','/img/user_none.jpg','SassyMamaInLA');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (376,0,'Tim Cogshell','http://lorempixel.com/50/50/people/','CineGods.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (377,0,'Ed Power','/img/user_none.jpg','Irish Independent');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (378,0,'Nigel Andrews','http://lorempixel.com/50/50/people/','Financial Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (379,0,'Gregory Wakeman','/img/user_none.jpg','Metro');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (380,0,'Sandra Hall','http://lorempixel.com/50/50/people/','Sydney Morning Herald');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (381,0,'Ira Madison III','/img/user_none.jpg','The Daily Beast');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (382,1,'Peter Howell','http://lorempixel.com/50/50/people/','Toronto Star');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (383,0,'Leigh Paatsch','/img/user_none.jpg','Herald Sun (Australia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (384,0,'Richard Lawson','http://lorempixel.com/50/50/people/','Vanity Fair');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (385,0,'Hugh Armitage','/img/user_none.jpg','Digital Spy');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (386,1,'Stephen Whitty','http://lorempixel.com/50/50/people/','New York Daily News');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (387,0,'Rebecca Pahle','/img/user_none.jpg','Film Journal International');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (388,0,'Donald Clarke','http://lorempixel.com/50/50/people/','Irish Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (389,0,'James Mottram','/img/user_none.jpg','South China Morning Post');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (390,0,'Jeanne Kaplan','http://lorempixel.com/50/50/people/','Kaplan vs. Kaplan');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (391,0,'David Kaplan','/img/user_none.jpg','Kaplan vs. Kaplan');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (392,0,'Cameron Williams','http://lorempixel.com/50/50/people/','The Brag');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (393,0,'Julian Roman','/img/user_none.jpg','MovieWeb');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (394,0,'Jordan Hoffman','http://lorempixel.com/50/50/people/','Popular Mechanics');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (395,0,'Kristy Puchko','/img/user_none.jpg','CBR');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (396,0,'Dave Schilling','http://lorempixel.com/50/50/people/','Birth.Movies.Death.');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (397,0,'Princess Weekes','/img/user_none.jpg','The Mary Sue');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (398,0,'Travis Johnson','http://lorempixel.com/50/50/people/','FILMINK (Australia)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (399,1,'Stephanie Zacharek','/img/user_none.jpg','TIME Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (400,1,'Frank Lovece','http://lorempixel.com/50/50/people/','Newsday');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (401,0,'Mark Hughes','/img/user_none.jpg','Forbes');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (402,0,'Fred Topel','http://lorempixel.com/50/50/people/','Monsters and Critics');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (403,0,'Tonja Renee Stidhum','/img/user_none.jpg','Shadow and Act');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (404,0,'Wilson Morales','http://lorempixel.com/50/50/people/','BlackFilm.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (405,0,'Pete Hammond','/img/user_none.jpg','Deadline Hollywood Daily');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (406,0,'Neil Soans','http://lorempixel.com/50/50/people/','The Times of India');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (407,0,'Kristian Harloff','/img/user_none.jpg','Schmoes Know');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (408,0,'Tim Grierson','http://lorempixel.com/50/50/people/','Screen International');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (409,0,'Katherine McLaughlin','/img/user_none.jpg','SciFiNow');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (410,0,'Emma Simmonds','http://lorempixel.com/50/50/people/','Radio Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (411,1,'Liz Braun','/img/user_none.jpg','Toronto Sun');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (412,0,'Rodrigo Perez','http://lorempixel.com/50/50/people/','The Playlist');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (413,1,'Jake Coyle','/img/user_none.jpg','Associated Press');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (414,1,'David Ehrlich','http://lorempixel.com/50/50/people/','indieWire');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (415,0,'Jason Guerrasio','/img/user_none.jpg','Business Insider');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (416,0,'Haleigh Foutch','http://lorempixel.com/50/50/people/','Collider');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (417,0,'Ashley Menzel','/img/user_none.jpg','We Live Entertainment');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (418,0,'Jamie Broadnax','http://lorempixel.com/50/50/people/','Black Girl Nerds');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (419,1,'Brian Lowry','/img/user_none.jpg','CNN.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (420,0,'Don Kaye','http://lorempixel.com/50/50/people/','Den of Geek');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (421,0,'Angie Han','/img/user_none.jpg','Mashable');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (422,0,'Olive Pometsey','http://lorempixel.com/50/50/people/','GQ Magazine [UK]');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (423,0,'Scott Menzel','/img/user_none.jpg','We Live Entertainment');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (424,0,'Robbie Collin','http://lorempixel.com/50/50/people/','Daily Telegraph (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (425,0,'Courtney Howard','/img/user_none.jpg','Fresh Fiction');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (426,0,'Todd VanDerWerff','http://lorempixel.com/50/50/people/','Vox');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (427,1,'Alonso Duralde','/img/user_none.jpg','TheWrap');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (428,0,'Kevin Maher','http://lorempixel.com/50/50/people/','Times (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (429,1,'Kenneth Turan','/img/user_none.jpg','Los Angeles Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (430,0,'Geoffrey Macnab','http://lorempixel.com/50/50/people/','Independent (UK)');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (431,1,'David Edelstein','/img/user_none.jpg','New York Magazine/Vulture');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (432,1,'Manohla Dargis','http://lorempixel.com/50/50/people/','New York Times');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (433,0,'Conner Schwerdtfeger','/img/user_none.jpg','CinemaBlend');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (434,1,'Brian Truitt','http://lorempixel.com/50/50/people/','USA Today');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (435,0,'Nicholas Barber','/img/user_none.jpg','BBC.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (436,1,'Peter Bradshaw','http://lorempixel.com/50/50/people/','Guardian');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (437,0,'Mike Ryan','/img/user_none.jpg','Uproxx');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (438,0,'Joelle Monique','http://lorempixel.com/50/50/people/','Polygon');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (439,1,'Peter Debruge','/img/user_none.jpg','Variety');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (440,0,'Marc Bernardin','http://lorempixel.com/50/50/people/','Nerdist');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (441,1,'Leah Greenblatt','/img/user_none.jpg','Entertainment Weekly');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (442,0,'Justin Craig','http://lorempixel.com/50/50/people/','FoxNews.com');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (443,1,'Todd McCarthy','/img/user_none.jpg','Hollywood Reporter');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (444,1,'Peter Travers','http://lorempixel.com/50/50/people/','Rolling Stone');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (445,0,'Kevin N. Laforest','/img/user_none.jpg','Extra Beurre');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (446,0,'Jimi Famurewa','http://lorempixel.com/50/50/people/','Empire Magazine');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (447,0,'Bryan Bishop','/img/user_none.jpg','The Verge');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (448,0,'Jim Vejvoda','http://lorempixel.com/50/50/people/','IGN Movies');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (449,0,'Scott Mendelson','/img/user_none.jpg','Forbes');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (450,0,'Matt Singer','http://lorempixel.com/50/50/people/','ScreenCrush');
INSERT INTO `rt.critics` (`id`,`top_critic`,`name`,`img_url`,`organization`) VALUES (451,0,'Clay Cane','/img/user_none.jpg','News One');
